// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWmbF37VFk5PSkGMtrIaZUUjLl9oP9vU',
    appId: '1:709889896038:android:37c5f0ea5b732c08e8c7a7',
    messagingSenderId: '709889896038',
    projectId: 'casa-50155',
    databaseURL: 'https://casa-50155-default-rtdb.firebaseio.com',
    storageBucket: 'casa-50155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAunecIZ7Xtx68YQjX2KBycLob1fxb5s',
    appId: '1:709889896038:ios:1685275dda6de331e8c7a7',
    messagingSenderId: '709889896038',
    projectId: 'casa-50155',
    databaseURL: 'https://casa-50155-default-rtdb.firebaseio.com',
    storageBucket: 'casa-50155.appspot.com',
    iosClientId: '709889896038-9fg69ave8j4449800bk2stms69a0r9fe.apps.googleusercontent.com',
    iosBundleId: 'com.softwareCasa.casa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAunecIZ7Xtx68YQjX2KBycLob1fxb5s',
    appId: '1:709889896038:ios:f60859f7f8e21740e8c7a7',
    messagingSenderId: '709889896038',
    projectId: 'casa-50155',
    databaseURL: 'https://casa-50155-default-rtdb.firebaseio.com',
    storageBucket: 'casa-50155.appspot.com',
    iosBundleId: 'y',
  );
}
